version: "3"
services:
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - "5002:5002"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
